#define ERR_FOPEN "Error opening log file"
#define ERR_MKFIFO "Error creating named pipe"
#define ERR_OPEN "Error opening pipe descriptor"
#define ERR_DUP "Error duping descriptor"
#define ERR_CLOSE "Error closing pipe descriptor"
#define ERR_WRITE "Error writing to pipe"
#define ERR_READ "Error reading from pipe"
#define ERR_UNLINK "Error unlinking pipe"
#define ERR_SIGN "Error arming signal"
#define ERR_KILL "Error sending signal"
#define ERR_COND "Error creating condition variables"
#define ERR_MTXINIT "Error initializing mutex"
#define ERR_MTHREAD "Error creating thread"
#define ERR_CPROC "Error creating child process"
#define ERR_FORK "Erro forking process"
